export function initialProducts() {
  return [
    {
      id: 'p1',
      name: 'Trades (Raw)',
      topic: 'trades.raw',
      owner: 'cm-trading',
      description: 'Raw trade events from execution systems.',
      tags: ['trades', 'execution', 'raw'],
      schema: { type: 'record', fields: [{ name: 'tradeId', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'qty', type: 'int' }, { name: 'px', type: 'double' }] },
      messagesPerSec: 180,
    },
    {
      id: 'p2',
      name: 'Trades (Enriched)',
      topic: 'trades.enriched',
      owner: 'cm-trading',
      description: 'Trades enriched with reference data and FX conversions.',
      tags: ['trades', 'enriched', 'fx'],
      schema: { type: 'record', fields: [{ name: 'tradeId', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'notionalUsd', type: 'double' }, { name: 'risk', type: 'double' }] },
      messagesPerSec: 120,
    },
    {
      id: 'p3',
      name: 'Risk Metrics',
      topic: 'risk.metrics',
      owner: 'cm-risk',
      description: 'Aggregated risk measures across portfolios in near real-time.',
      tags: ['risk', 'var', 'greeks'],
      schema: { type: 'record', fields: [{ name: 'portfolio', type: 'string' }, { name: 'VaR', type: 'double' }, { name: 'Delta', type: 'double' }] },
      messagesPerSec: 60,
    },
    {
      id: 'p4',
      name: 'Market Data Tick Stream',
      topic: 'md.ticks',
      owner: 'cm-mdm',
      description: 'Real-time Level 1/2 quotes and trades across venues.',
      tags: ['market-data', 'quotes', 'ticks'],
      schema: { type: 'record', fields: [{ name: 'symbol', type: 'string' }, { name: 'bid', type: 'double' }, { name: 'ask', type: 'double' }, { name: 'last', type: 'double' }] },
      messagesPerSec: 500,
    },
    {
      id: 'p5',
      name: 'Options Greeks',
      topic: 'options.greeks',
      owner: 'cm-derivs',
      description: 'Per-instrument option Greeks computed via streaming pricers.',
      tags: ['options', 'greeks', 'derivatives'],
      schema: { type: 'record', fields: [{ name: 'symbol', type: 'string' }, { name: 'delta', type: 'double' }, { name: 'gamma', type: 'double' }, { name: 'vega', type: 'double' }, { name: 'theta', type: 'double' }] },
      messagesPerSec: 220,
    },
    {
      id: 'p6',
      name: 'FX Rates (Enriched)',
      topic: 'fx.enriched',
      owner: 'cm-fx',
      description: 'Cross-currency rates with liquidity tiers and spreads.',
      tags: ['fx', 'fxspot', 'rates'],
      schema: { type: 'record', fields: [{ name: 'ccyPair', type: 'string' }, { name: 'bid', type: 'double' }, { name: 'ask', type: 'double' }, { name: 'liquidity', type: 'string' }] },
      messagesPerSec: 340,
    },
    {
      id: 'p7',
      name: 'Corporate Actions',
      topic: 'refdata.corp_actions',
      owner: 'cm-refdata',
      description: 'Stream of corporate actions and reference data updates.',
      tags: ['reference-data', 'corp-actions'],
      schema: { type: 'record', fields: [{ name: 'event', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'effectiveDate', type: 'string' }] },
      messagesPerSec: 15,
    },
  ]
}
