export function initialProducts() {
  return [
    {
      id: 'p1',
  type: 'stream',
      name: 'Trades (Raw)',
      topic: 'trades.raw',
      owner: 'cm-trading',
      description: 'Raw trade events from execution systems.',
      tags: ['trades', 'execution', 'raw'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'tradeId', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'qty', type: 'int' }, { name: 'px', type: 'double' }] },
  messagesPerSec: 180,
  retentionDays: 7,
    },
    {
      id: 'p2',
  type: 'stream',
      name: 'Trades (Enriched)',
      topic: 'trades.enriched',
      owner: 'cm-trading',
      description: 'Trades enriched with reference data and FX conversions.',
      tags: ['trades', 'enriched', 'fx'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'tradeId', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'notionalUsd', type: 'double' }, { name: 'risk', type: 'double' }] },
  messagesPerSec: 120,
  retentionDays: 7,
    },
    {
      id: 'p3',
  type: 'stream',
      name: 'Risk Metrics',
      topic: 'risk.metrics',
      owner: 'cm-risk',
      description: 'Aggregated risk measures across portfolios in near real-time.',
      tags: ['risk', 'var', 'greeks'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'portfolio', type: 'string' }, { name: 'VaR', type: 'double' }, { name: 'Delta', type: 'double' }] },
  messagesPerSec: 60,
  retentionDays: 14,
    },
    {
      id: 'p4',
  type: 'stream',
      name: 'Market Data Tick Stream',
      topic: 'md.ticks',
      owner: 'cm-mdm',
      description: 'Real-time Level 1/2 quotes and trades across venues.',
      tags: ['market-data', 'quotes', 'ticks'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'symbol', type: 'string' }, { name: 'bid', type: 'double' }, { name: 'ask', type: 'double' }, { name: 'last', type: 'double' }] },
  messagesPerSec: 500,
  retentionDays: 2,
    },
    {
      id: 'p5',
  type: 'stream',
      name: 'Options Greeks',
      topic: 'options.greeks',
      owner: 'cm-derivs',
      description: 'Per-instrument option Greeks computed via streaming pricers.',
      tags: ['options', 'greeks', 'derivatives'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'symbol', type: 'string' }, { name: 'delta', type: 'double' }, { name: 'gamma', type: 'double' }, { name: 'vega', type: 'double' }, { name: 'theta', type: 'double' }] },
  messagesPerSec: 220,
  retentionDays: 7,
    },
    {
      id: 'p6',
  type: 'stream',
      name: 'FX Rates (Enriched)',
      topic: 'fx.enriched',
      owner: 'cm-fx',
      description: 'Cross-currency rates with liquidity tiers and spreads.',
      tags: ['fx', 'fxspot', 'rates'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'ccyPair', type: 'string' }, { name: 'bid', type: 'double' }, { name: 'ask', type: 'double' }, { name: 'liquidity', type: 'double' }] },
  messagesPerSec: 340,
  retentionDays: 3,
    },
    {
      id: 'p7',
  type: 'stream',
      name: 'Corporate Actions',
      topic: 'refdata.corp_actions',
      owner: 'cm-refdata',
      description: 'Stream of corporate actions and reference data updates.',
      tags: ['reference-data', 'corp-actions'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'event', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'effectiveDate', type: 'string' }] },
  messagesPerSec: 15,
  retentionDays: 30,
    },
    // Analytics products
    {
      id: 'a1',
  type: 'analytics',
      name: 'PnL by Desk (5m Window)',
      owner: 'cm-analytics',
      description: 'Streaming aggregated PnL per desk computed over sliding 5m windows.',
      tags: ['analytics', 'pnl', 'windowed'],
  schema: { type: 'table', columns: [{ name: 'desk', type: 'string' }, { name: 'pnl', type: 'double' }, { name: 'windowEnd', type: 'timestamp' }] },
      messagesPerSec: 35,
    },
    {
      id: 'a2',
  type: 'analytics',
      name: 'Order Fill Rate (1m KPI)',
      owner: 'cm-analytics',
      description: 'Fill rate KPI per symbol and venue computed in near real-time.',
      tags: ['analytics', 'kpi', 'orders'],
  schema: { type: 'table', columns: [{ name: 'symbol', type: 'string' }, { name: 'venue', type: 'string' }, { name: 'fillRate', type: 'double' }, { name: 'windowEnd', type: 'timestamp' }] },
      messagesPerSec: 48,
    },
    {
      id: 'a3',
  type: 'analytics',
      name: 'Latency SLO Breaches',
      owner: 'cm-observability',
      description: 'Stream of SLO breach events for low-latency workflows.',
      tags: ['analytics', 'slo', 'observability'],
  schema: { type: 'table', columns: [{ name: 'service', type: 'string' }, { name: 'p99LatencyMs', type: 'double' }, { name: 'breach', type: 'boolean' }] },
      messagesPerSec: 8,
    },
  ]
}
