export function initialProducts() {
  return [
    {
      id: 'p1',
  type: 'stream',
      name: 'Sophis Trades',
      topic: 'trades.sophis.raw',
      owner: 'Navdeep Brar',
      description: 'Raw trade events from execution systems.',
      tags: ['trades', 'execution', 'raw'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'tradeId', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'qty', type: 'int' }, { name: 'px', type: 'double' }] },
  messagesPerSec: 180,
  retentionDays: 7,
    },
    {
      id: 'p4',
      type: 'stream',
      name: 'Market Data',
      topic: 'md.ticks',
      owner: 'Javier Vazquez',
      description: 'Real-time Level 1/2 quotes and trades across venues.',
      tags: ['market-data', 'quotes', 'ticks'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'symbol', type: 'string' }, { name: 'bid', type: 'double' }, { name: 'ask', type: 'double' }, { name: 'last', type: 'double' }] },
  messagesPerSec: 500,
  retentionDays: 2,
    },
{
      id: 'p9',
      type: 'analytics',
      name: 'EOD Market Data',
      owner: 'Javier Vazquez',
      description: 'End of Day quotes across venues.',
      tags: ['market-data', 'quotes', 'eod'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'symbol', type: 'string' }, { name: 'bid', type: 'double' }, { name: 'ask', type: 'double' }, { name: 'last', type: 'double' }] },
  messagesPerSec: 500
    },
    {
      id: 'p2',
  type: 'stream',
      name: 'Murex Trades',
      topic: 'trades.murex.enriched',
      owner: 'Tim James',
      description: 'Trades enriched with reference data and FX conversions.',
      tags: ['trades', 'enriched', 'fx', ],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'tradeId', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'notionalUsd', type: 'double' }, { name: 'risk', type: 'double' }] },
  messagesPerSec: 120,
  retentionDays: 7,
    },
    {
      id: 'p3',
  type: 'stream',
      name: 'Risk Metrics',
      topic: 'risk.metrics',
      owner: 'Eleonor Morrison',
      description: 'Aggregated risk measures across portfolios in near real-time.',
      tags: ['risk', 'var', 'greeks'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'portfolio', type: 'string' }, { name: 'VaR', type: 'double' }, { name: 'Delta', type: 'double' }] },
  messagesPerSec: 60,
  retentionDays: 14,
    },
    {
      id: 'p5',
  type: 'stream',
      name: 'AML Signals',
      topic: 'aml.signals',
      owner: 'Dan Bosman',
      description: 'Anti Money Laundering signals for transaction monitoring.',
      tags: ['fraud', 'aml', 'signals'],
    schema: {
      type: 'record',
      fields: [
        { name: 'timestamp', type: 'timestamp' },
        { name: 'transactionId', type: 'string' },
        { name: 'customerId', type: 'string' },
        { name: 'amount', type: 'double' },
        { name: 'currency', type: 'string' },
        { name: 'signalType', type: 'string' },
        { name: 'riskScore', type: 'double' },
        { name: 'status', type: 'string' },
        { name: 'details', type: 'string' }
      ]
    },
  messagesPerSec: 220,
  retentionDays: 7,
    },
    {
      id: 'p6',
  type: 'stream',
      name: 'FX Rates',
      topic: 'fx.enriched',
      owner: 'Tim James',
      description: 'Cross-currency rates with liquidity tiers and spreads.',
      tags: ['fx', 'fxspot', 'rates'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'ccyPair', type: 'string' }, { name: 'bid', type: 'double' }, { name: 'ask', type: 'double' }, { name: 'liquidity', type: 'double' }] },
  messagesPerSec: 340,
  retentionDays: 3,
    },
    {
      id: 'p7',
  type: 'stream',
      name: 'Corporate Actions',
      topic: 'refdata.corp_actions',
      owner: 'Brendan White',
      description: 'Stream of corporate actions and reference data updates.',
      tags: ['reference-data', 'corp-actions'],
  schema: { type: 'record', fields: [{ name: 'timestamp', type: 'timestamp' }, { name: 'event', type: 'string' }, { name: 'symbol', type: 'string' }, { name: 'effectiveDate', type: 'string' }] },
  messagesPerSec: 15,
  retentionDays: 30,
    },
    // Analytics products
    {
      id: 'a1',
  type: 'analytics',
      name: 'PnL by Desk (Daily)',
      owner: 'Tim James',
      description: 'Aggregated PnL per desk computed daily',
      tags: ['analytics', 'pnl', 'windowed'],
  schema: { type: 'table', columns: [{ name: 'desk', type: 'string' }, { name: 'pnl', type: 'double' }, { name: 'windowEnd', type: 'timestamp' }] },
      messagesPerSec: 35,
    },
    {
      id: 'a2',
  type: 'stream',
      name: 'Payments',
      owner: 'Dan Bosman',
        description: 'Bank transactions made by customers, including payment details and status.',
        tags: ['payments', 'transactions', 'customers'],
    schema: {
      type: 'table',
      columns: [
        { name: 'paymentId', type: 'string' },
        { name: 'customerId', type: 'string' },
        { name: 'amount', type: 'double' },
        { name: 'currency', type: 'string' },
        { name: 'timestamp', type: 'timestamp' },
        { name: 'status', type: 'string' },
        { name: 'bankAccount', type: 'string' },
        { name: 'recipient', type: 'string' },
        { name: 'method', type: 'string' }
      ]
    },
      messagesPerSec: 48,
    },
    {
      id: 'a3',
      type: 'stream',
      name: 'Trading Ideas',
      owner: 'Vidhya Gilani',
        description: 'Trading ideas identified and published by the Research team.',
        tags: ['ideas', 'research', 'sales'],
    schema: {
      type: 'table',
      columns: [
        { name: 'ideaId', type: 'string' },
        { name: 'researcher', type: 'string' },
        { name: 'symbol', type: 'string' },
        { name: 'ideaType', type: 'string' },
        { name: 'rationale', type: 'string' },
        { name: 'targetPrice', type: 'double' },
        { name: 'stopLoss', type: 'double' },
        { name: 'publishedAt', type: 'timestamp' },
        { name: 'status', type: 'string' }
      ]
    },
      messagesPerSec: 8,
      retentionDays: 7
    },
  ]
}
